import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import {
  getDqReportData, getDgSummaryReportData, getBusinessDomains, getDataSourcesLite,
  type DqDrillDownRow, type DgGapRow,
} from "@/lib/queries/reports";
import * as XLSX from "xlsx";

const REPORT_NAMES: Record<string, string> = { R2_DQ: "Data Quality", R8_DG_SUMMARY: "DG Executive Summary" };

export async function GET(req: Request, { params }: { params: { reportCode: string } }) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const reportCode = params.reportCode;
  if (!REPORT_NAMES[reportCode]) return NextResponse.json({ error: "Unknown report" }, { status: 404 });

  const { searchParams } = new URL(req.url);
  const domainGlossaryId = searchParams.get("domain") ? Number(searchParams.get("domain")) : undefined;
  const sourceId = searchParams.get("source") ? Number(searchParams.get("source")) : undefined;
  const ownerId = searchParams.get("owner") ?? undefined;
  const filters = { domainGlossaryId, sourceId, ownerId };

  const [domains, sources] = await Promise.all([getBusinessDomains(), getDataSourcesLite()]);
  const domainName = domainGlossaryId != null ? (domains.find((d) => d.glossaryId === domainGlossaryId)?.name ?? "All") : "All";
  const sourceName = sourceId != null ? (sources.find((s) => s.dataSourceId === sourceId)?.sourceName ?? "All") : "All";

  const data = reportCode === "R2_DQ"
    ? await getDqReportData(filters, { limit: 1000, offset: 0 })
    : await getDgSummaryReportData(filters, { limit: 1000, offset: 0 });

  const kpiRows = data.kpis.map((k) => ({
    "KPI": k.nameEn,
    "Value": k.value,
    "Target": k.targetValue ?? "",
    "Format": k.format,
  }));

  const drillRows = reportCode === "R2_DQ"
    ? (data.drillDown as DqDrillDownRow[]).map((r) => ({
        "Rule": r.ruleName,
        "Dimension": r.dimensionName,
        "Severity": r.severity,
        "Status": r.statusCode,
        "Score": r.score ?? "",
        "Table": r.entityName,
        "Source": r.sourceName,
        "Domain": r.domainName,
        "Executed At": r.executedAt,
        "Age (days)": r.ageDays,
      }))
    : (data.drillDown as DgGapRow[]).map((r) => ({
        "Table": r.entityName,
        "Source": r.sourceName,
        "Domain": r.domainName,
        "Has Owner": r.hasOwner ? "Yes" : "No",
        "Has Steward": r.hasSteward ? "Yes" : "No",
        "Certified": r.isCertified ? "Yes" : "No",
        "Columns Missing Description": r.missingDescCount,
      }));

  const metaRows = [
    { Field: "Report", Value: REPORT_NAMES[reportCode] },
    { Field: "Generated By", Value: session.fullName },
    { Field: "Generated At", Value: new Date().toISOString() },
    { Field: "Business Domain Filter", Value: domainName },
    { Field: "Data Source Filter", Value: sourceName },
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(metaRows), "Info");
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(kpiRows), "KPIs");
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(drillRows), "Drill-down");

  const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  const fileName = `${reportCode}_${new Date().toISOString().slice(0, 10)}.xlsx`;

  return new Response(buf, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${fileName}"`,
    },
  });
}
