import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { getBusinessDomains, getDataSourcesLite, logReportExport } from "@/lib/queries/reports";
import { REPORT_REGISTRY } from "@/lib/reports/report-registry";
import { applyStewardScope } from "@/lib/reports/access";
import * as XLSX from "xlsx";

export async function GET(req: Request, { params }: { params: { reportCode: string } }) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const descriptor = REPORT_REGISTRY[params.reportCode];
  if (!descriptor) return NextResponse.json({ error: "Unknown report" }, { status: 404 });

  const { searchParams } = new URL(req.url);
  const domainGlossaryId = searchParams.get("domain") ? Number(searchParams.get("domain")) : undefined;
  const sourceId = searchParams.get("source") ? Number(searchParams.get("source")) : undefined;
  const ownerId = searchParams.get("owner") ?? undefined;

  const filters = await applyStewardScope(session, { domainGlossaryId, sourceId, ownerId });
  const [data, domains, sources] = await Promise.all([
    descriptor.fetch(filters, { limit: 1000, offset: 0 }),
    getBusinessDomains(),
    getDataSourcesLite(),
  ]);
  const domainName = filters.domainGlossaryId != null ? (domains.find((d) => d.glossaryId === filters.domainGlossaryId)?.name ?? "All") : "All";
  const sourceName = filters.sourceId != null ? (sources.find((s) => s.dataSourceId === filters.sourceId)?.sourceName ?? "All") : "All";

  const kpiRows = data.kpis.map((k) => ({
    "KPI": k.nameEn,
    "Value": k.value,
    "Target": k.targetValue ?? "",
    "Format": k.format,
  }));

  const drillRows = data.drillDown.map((row) => {
    const out: Record<string, string | number> = {};
    for (const col of descriptor.drillDownColumns) out[col.label] = col.get(row);
    return out;
  });

  const metaRows = [
    { Field: "Report", Value: descriptor.label },
    { Field: "Generated By", Value: session.fullName },
    { Field: "Generated At", Value: new Date().toISOString() },
    { Field: "Business Domain Filter", Value: domainName },
    { Field: "Data Source Filter", Value: sourceName },
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(metaRows), "Info");
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(kpiRows), "KPIs");
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(drillRows), "Drill-down");

  const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  await logReportExport(descriptor.code, session.userId, filters, "XLSX");
  const fileName = `${descriptor.code}_${new Date().toISOString().slice(0, 10)}.xlsx`;

  return new Response(buf, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="${fileName}"`,
    },
  });
}
