import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { getBusinessDomains, getDataSourcesLite, logReportExport } from "@/lib/queries/reports";
import { REPORT_REGISTRY } from "@/lib/reports/report-registry";
import { applyStewardScope } from "@/lib/reports/access";
import { createJob, finishJob, failJob } from "@/lib/queries/background-jobs";
import * as XLSX from "xlsx";
import type { SessionUser } from "@/lib/types";

const JOB_TYPE_REPORT_EXPORT_XLSX = "REPORT_EXPORT_XLSX";

async function runExport(
  jobId: number, session: SessionUser, reportCode: string,
  filterInput: { domainGlossaryId?: number; sourceId?: number; ownerId?: string },
): Promise<void> {
  try {
    const descriptor = REPORT_REGISTRY[reportCode];
    if (!descriptor) throw new Error("Unknown report");

    const filters = await applyStewardScope(session, filterInput);
    const [data, domains, sources] = await Promise.all([
      descriptor.fetch(filters, { limit: 1000, offset: 0 }),
      getBusinessDomains(),
      getDataSourcesLite(),
    ]);
    const domainName = filters.domainGlossaryId != null ? (domains.find((d) => d.glossaryId === filters.domainGlossaryId)?.name ?? "All") : "All";
    const sourceName = filters.sourceId != null ? (sources.find((s) => s.dataSourceId === filters.sourceId)?.sourceName ?? "All") : "All";

    const kpiRows = data.kpis.map((k) => ({ "KPI": k.nameEn, "Value": k.value, "Target": k.targetValue ?? "", "Format": k.format }));
    const drillRows = data.drillDown.map((row) => {
      const out: Record<string, string | number> = {};
      for (const col of descriptor.drillDownColumns) out[col.label] = col.get(row);
      return out;
    });
    const metaRows = [
      { Field: "Report", Value: descriptor.label },
      { Field: "Generated By", Value: session.fullName },
      { Field: "Generated At", Value: new Date().toISOString() },
      { Field: "Business Domain Filter", Value: domainName },
      { Field: "Data Source Filter", Value: sourceName },
    ];

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(metaRows), "Info");
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(kpiRows), "KPIs");
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(drillRows), "Drill-down");
    const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

    await logReportExport(descriptor.code, session.userId, filters, "XLSX");
    const fileName = `${descriptor.code}_${new Date().toISOString().slice(0, 10)}.xlsx`;

    await finishJob(jobId, {
      resultFileData: buf,
      resultFileName: fileName,
      resultFileMimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      resultJson: { kpis: data.kpis.length, drillDownRows: data.drillDown.length },
    });
  } catch (e) {
    await failJob(jobId, (e as Error).message);
  }
}

export async function POST(req: Request, { params }: { params: { reportCode: string } }) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const descriptor = REPORT_REGISTRY[params.reportCode];
  if (!descriptor) return NextResponse.json({ error: "Unknown report" }, { status: 404 });

  const body = await req.json().catch(() => ({})) as { domainGlossaryId?: number; sourceId?: number; ownerId?: string };
  const jobId = await createJob(JOB_TYPE_REPORT_EXPORT_XLSX, { reportCode: params.reportCode, ...body }, session.userId);
  void runExport(jobId, session, params.reportCode, body);

  return NextResponse.json({ jobId }, { status: 202 });
}
