import type { KpiCardData, TrendPoint } from "../queries/reports";
import { getRagStatus, type RagStatus } from "./rag";

const RAG_HEX: Record<RagStatus, { border: string; bg: string; text: string }> = {
  green: { border: "#34d399", bg: "#ecfdf5", text: "#059669" },
  amber: { border: "#fbbf24", bg: "#fffbeb", text: "#d97706" },
  red:   { border: "#f87171", bg: "#fef2f2", text: "#dc2626" },
};

function escapeHtml(v: unknown): string {
  return String(v ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

function formatValue(value: number, format: KpiCardData["format"]): string {
  if (format === "PERCENT") return `${value}%`;
  if (format === "DAYS") return `${value}d`;
  return String(value);
}

// Pure SVG path-math, deliberately not reusing components/reports/TrendChart.tsx
// (a client component built on React hooks) so this can run server-side inside the
// PDF route with no React render pass involved.
function buildTrendSvg(data: TrendPoint[], target: number | null): string {
  if (data.length < 2) {
    return `<div style="padding:24px 0;color:#8089b3;font-size:12px;text-align:center;">No trend history yet — capture a snapshot to start building the trend line.</div>`;
  }
  const W = 480, H = 140;
  const PAD = { l: 28, r: 14, t: 14, b: 22 };
  const cW = W - PAD.l - PAD.r, cH = H - PAD.t - PAD.b;
  const values = data.map((d) => d.value);
  const yMin = Math.min(0, ...values, target ?? 0);
  const yMax = Math.max(100, ...values, target ?? 0);
  const toY = (v: number) => PAD.t + cH - ((v - yMin) / (yMax - yMin || 1)) * cH;
  const toX = (i: number) => PAD.l + (data.length <= 1 ? cW / 2 : (i / (data.length - 1)) * cW);
  const path = data.map((d, i) => `${i === 0 ? "M" : "L"} ${toX(i).toFixed(1)} ${toY(d.value).toFixed(1)}`).join(" ");
  const dots = data.map((d, i) => `<circle cx="${toX(i).toFixed(1)}" cy="${toY(d.value).toFixed(1)}" r="3" fill="#6058A0"/>`).join("");
  const targetLine = target != null
    ? `<line x1="${PAD.l}" x2="${W - PAD.r}" y1="${toY(target).toFixed(1)}" y2="${toY(target).toFixed(1)}" stroke="#c0c4e0" stroke-width="1" stroke-dasharray="4 3"/>`
    : "";
  return `<svg viewBox="0 0 ${W} ${H}" width="100%" height="140">${targetLine}<path d="${path}" fill="none" stroke="#6058A0" stroke-width="2.4" stroke-linecap="round"/>${dots}</svg>`;
}

const LABELS = {
  en: { generatedBy: "Generated By", generatedAt: "Generated At", domain: "Business Domain", source: "Data Source", trend: "12-Month Trend", detail: "Detail", allDomains: "All Domains", allSources: "All Sources" },
  ar: { generatedBy: "أُنشئ بواسطة", generatedAt: "تاريخ الإنشاء", domain: "النطاق التجاري", source: "مصدر البيانات", trend: "الاتجاه خلال 12 شهراً", detail: "التفاصيل", allDomains: "كل النطاقات", allSources: "كل المصادر" },
};

export function buildReportPdfHtml(opts: {
  lang: "en" | "ar";
  reportLabel: string;
  generatedBy: string;
  domainName: string | null;
  sourceName: string | null;
  kpis: KpiCardData[];
  trend: TrendPoint[];
  primaryTarget: number | null;
  drillDownColumns: { label: string; get: (row: Record<string, unknown>) => string | number }[];
  drillDownRows: Record<string, unknown>[];
}): string {
  const t = LABELS[opts.lang];
  const dir = opts.lang === "ar" ? "rtl" : "ltr";

  const kpiCards = opts.kpis.map((k) => {
    const rag = getRagStatus(k.value, k.targetValue, k.direction);
    const colors = RAG_HEX[rag];
    const name = opts.lang === "ar" ? (k.nameAr ?? k.nameEn) : k.nameEn;
    return `
      <div style="border-${dir === "rtl" ? "right" : "left"}:4px solid ${colors.border};background:${colors.bg};padding:10px 14px;border-radius:6px;">
        <div style="font-size:20px;font-weight:800;color:${colors.text};">${formatValue(k.value, k.format)}</div>
        <div style="font-size:10px;color:#8089b3;text-transform:uppercase;letter-spacing:0.05em;margin-top:2px;">${escapeHtml(name)}</div>
      </div>`;
  }).join("");

  const drillHeader = opts.drillDownColumns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join("");
  const drillRows = opts.drillDownRows.slice(0, 100).map((row) =>
    `<tr>${opts.drillDownColumns.map((c) => `<td>${escapeHtml(c.get(row))}</td>`).join("")}</tr>`
  ).join("");

  return `<!doctype html>
<html dir="${dir}" lang="${opts.lang}">
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: ${opts.lang === "ar" ? "'Noto Sans Arabic', 'Segoe UI', Tahoma, sans-serif" : "'Inter', 'Segoe UI', Arial, sans-serif"}; margin: 0; padding: 32px; color: #0f1238; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #e6e9f5; padding-bottom: 12px; margin-bottom: 20px; }
  .brand { font-size: 12px; font-weight: 700; letter-spacing: 0.16em; color: #201C55; }
  .title { font-size: 20px; font-weight: 800; color: #201C55; margin-top: 4px; }
  .meta { font-size: 10px; color: #8089b3; text-align: ${dir === "rtl" ? "left" : "right"}; line-height: 1.6; }
  .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 20px; }
  .section-title { font-size: 12px; font-weight: 700; color: #0f1238; margin: 20px 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  th, td { text-align: ${dir === "rtl" ? "right" : "left"}; padding: 5px 8px; border-bottom: 1px solid #eef0f8; }
  th { color: #8089b3; text-transform: uppercase; font-size: 9px; letter-spacing: 0.05em; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">BAYANATIX</div>
      <div class="title">${escapeHtml(opts.reportLabel)}</div>
    </div>
    <div class="meta">
      <div>${t.generatedBy}: ${escapeHtml(opts.generatedBy)}</div>
      <div>${t.generatedAt}: ${new Date().toISOString().slice(0, 19).replace("T", " ")}</div>
      <div>${t.domain}: ${escapeHtml(opts.domainName ?? t.allDomains)}</div>
      <div>${t.source}: ${escapeHtml(opts.sourceName ?? t.allSources)}</div>
    </div>
  </div>

  <div class="kpi-grid">${kpiCards}</div>

  <div class="section-title">${t.trend}</div>
  ${buildTrendSvg(opts.trend, opts.primaryTarget)}

  <div class="section-title">${t.detail}</div>
  <table>
    <thead><tr>${drillHeader}</tr></thead>
    <tbody>${drillRows}</tbody>
  </table>
</body>
</html>`;
}
