-- 158: Québec Law 25 as a compliance framework.
-- "Law 25" (SQ 2021, c. 25, formerly Bill 64) modernised Québec's Act respecting the
-- protection of personal information in the private sector (CQLR c. P-39.1); its
-- provisions came into force in three stages (22 September 2022, 2023 and 2024).
-- 60 requirements in 11 domains, each phrased as an assessment question and carrying
-- the section of the Act it comes from (guidance column). Requirement definitions only —
-- every organisation records its own assessment. Stored the same way as PIPEDA
-- (COMPLIANCE_ONLY, one "Requirement" level, the standard status list).
-- Safe to run more than once.

BEGIN;

INSERT INTO bayanat.gov_compliance_frameworks (name, code, version, description, regulation_group_code, is_applicable_indicator, assessment_mode)
VALUES (
  'Québec Law 25', 'QC_LAW25', '2024',
  $t$Québec — Act respecting the protection of personal information in the private sector (CQLR c. P-39.1) as amended by Law 25 (SQ 2021, c. 25). Applies to enterprises that collect, hold, use or communicate personal information in the course of carrying on an enterprise in Québec. Overseen by the Commission d'accès à l'information (CAI). Administrative monetary penalties up to CA$10,000,000 or 2% of worldwide turnover; penal fines up to CA$25,000,000 or 4% of worldwide turnover.$t$,
  'INTERNATIONAL_STANDARDS', true, 'COMPLIANCE_ONLY'
)
ON CONFLICT (code) DO NOTHING;

INSERT INTO bayanat.gov_compliance_requirements
  (framework_id, req_code, domain, domain_en, domain_code, standard, standard_code, req_text, question_en, guidance,
   maturity_level, compliance_or_maturity, sort_order)
SELECT f.framework_id, v.req_code, v.domain, v.domain, v.domain_code, v.standard, v.standard, v.req_text, v.req_text, v.guidance,
       '0', 'Compliance', v.sort_order
FROM bayanat.gov_compliance_frameworks f
CROSS JOIN (VALUES
  ($t$LAW25.3.1.1-L0-0$t$, $t$Governance & Accountability$t$, $t$GOV$t$, $t$LAW25.3.1.1$t$, $t$Has the organization identified the person in charge of the protection of personal information (by default the person exercising the highest authority), and is any delegation of that function made in writing?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.1$t$, 0),
  ($t$LAW25.3.1.2-L0-1$t$, $t$Governance & Accountability$t$, $t$GOV$t$, $t$LAW25.3.1.2$t$, $t$Are the title and contact information of the person in charge of the protection of personal information published on the organization's website, or made available by another appropriate means if it has no website?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.1$t$, 1),
  ($t$LAW25.3.2.1-L0-2$t$, $t$Governance & Accountability$t$, $t$GOV$t$, $t$LAW25.3.2.1$t$, $t$Has the organization established and implemented governance policies and practices for personal information that are proportionate to the nature and scale of its activities and approved by the person in charge?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.2$t$, 2),
  ($t$LAW25.3.2.2-L0-3$t$, $t$Governance & Accountability$t$, $t$GOV$t$, $t$LAW25.3.2.2$t$, $t$Do the governance policies and practices provide a framework for keeping and destroying personal information, define the roles and responsibilities of personnel throughout the information life cycle, and provide a process for handling complaints?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.2$t$, 3),
  ($t$LAW25.3.2.3-L0-4$t$, $t$Governance & Accountability$t$, $t$GOV$t$, $t$LAW25.3.2.3$t$, $t$Is detailed information about these policies and practices published in simple and clear language on the organization's website?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.2$t$, 4),
  ($t$LAW25.20-L0-5$t$, $t$Governance & Accountability$t$, $t$GOV$t$, $t$LAW25.20$t$, $t$Is access to personal information within the organization limited to the employees and agents for whom it is necessary for the performance of their duties?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 20$t$, 5),
  ($t$LAW25.3.3.1-L0-6$t$, $t$Privacy Impact Assessments$t$, $t$PIA$t$, $t$LAW25.3.3.1$t$, $t$Does the organization conduct a privacy impact assessment for any project to acquire, develop or overhaul an information system or electronic service delivery system involving personal information?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.3$t$, 6),
  ($t$LAW25.3.3.2-L0-7$t$, $t$Privacy Impact Assessments$t$, $t$PIA$t$, $t$LAW25.3.3.2$t$, $t$Is the person in charge of the protection of personal information consulted from the outset of such projects, and is each assessment proportionate to the sensitivity, purpose, quantity, distribution and medium of the information?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.3$t$, 7),
  ($t$LAW25.3.3.3-L0-8$t$, $t$Privacy Impact Assessments$t$, $t$PIA$t$, $t$LAW25.3.3.3$t$, $t$Do such projects ensure that computerized personal information collected from the person concerned can be communicated to that person in a structured, commonly used technological format?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.3$t$, 8),
  ($t$LAW25.3.4-L0-9$t$, $t$Privacy Impact Assessments$t$, $t$PIA$t$, $t$LAW25.3.4$t$, $t$Are the protection measures suggested by the person in charge at any stage of a project (for example a steering committee, protection clauses in contracts, staff training) considered and recorded?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.4$t$, 9),
  ($t$LAW25.3.5.1-L0-10$t$, $t$Confidentiality Incidents$t$, $t$INC$t$, $t$LAW25.3.5.1$t$, $t$When there is cause to believe a confidentiality incident has occurred, does the organization take reasonable measures to reduce the risk of injury and to prevent new incidents of the same nature?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.5$t$, 10),
  ($t$LAW25.3.5.2-L0-11$t$, $t$Confidentiality Incidents$t$, $t$INC$t$, $t$LAW25.3.5.2$t$, $t$Where an incident presents a risk of serious injury, does the organization promptly notify the Commission d'accès à l'information and every person whose personal information is concerned?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.5$t$, 11),
  ($t$LAW25.3.6-L0-12$t$, $t$Confidentiality Incidents$t$, $t$INC$t$, $t$LAW25.3.6$t$, $t$Does the organization's incident definition cover unauthorized access, unauthorized use, unauthorized communication, loss, and any other breach of the protection of personal information?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.6$t$, 12),
  ($t$LAW25.3.7-L0-13$t$, $t$Confidentiality Incidents$t$, $t$INC$t$, $t$LAW25.3.7$t$, $t$When assessing the risk of serious injury, does the organization consider the sensitivity of the information, the anticipated consequences of its use and the likelihood that it will be used for injurious purposes, in consultation with the person in charge?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.7$t$, 13),
  ($t$LAW25.3.8-L0-14$t$, $t$Confidentiality Incidents$t$, $t$INC$t$, $t$LAW25.3.8$t$, $t$Does the organization keep a register of all confidentiality incidents, and can it provide a copy to the Commission d'accès à l'information on request?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.8$t$, 14),
  ($t$LAW25.4-L0-15$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.4$t$, $t$Does the organization collect personal information only for a serious and legitimate reason, and determine the purposes before collecting it?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 4$t$, 15),
  ($t$LAW25.5-L0-16$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.5$t$, $t$Is collection limited to the personal information necessary for the purposes determined, and carried out by lawful means?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 5$t$, 16),
  ($t$LAW25.6-L0-17$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.6$t$, $t$Is personal information collected from the person concerned, unless that person consents to collection from a third party or an exception provided by law applies?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 6$t$, 17),
  ($t$LAW25.8.1-L0-18$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.8.1$t$, $t$At or before collection, is the person informed of the purposes, the means of collection, the rights of access and rectification, and the right to withdraw consent to communication or use?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 8$t$, 18),
  ($t$LAW25.8.2-L0-19$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.8.2$t$, $t$Where applicable, is the person informed of the name of the third person for whom the information is collected, the third persons or categories of third persons to whom it may be communicated, and the possibility that it may be communicated outside Québec?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 8$t$, 19),
  ($t$LAW25.8.3-L0-20$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.8.3$t$, $t$On request, can the organization tell the person which personal information was collected, the categories of persons who have access to it, how long it will be kept, and how to contact the person in charge?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 8$t$, 20),
  ($t$LAW25.8.1-L0-21$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.8.1$t$, $t$Where technology with functions that identify, locate or profile a person is used to collect personal information, is the person informed beforehand of its use and of the means available to activate those functions?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 8.1$t$, 21),
  ($t$LAW25.8.2-L0-22$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.8.2$t$, $t$Where personal information is collected through technological means, is a confidentiality policy published in simple and clear language on the website, and are changes to it notified in the same way?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 8.2$t$, 22),
  ($t$LAW25.9.1-L0-23$t$, $t$Collection & Transparency$t$, $t$COL$t$, $t$LAW25.9.1$t$, $t$Do technological products or services offered to the public that have privacy settings provide the highest level of confidentiality by default, without any intervention by the person concerned?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 9.1$t$, 23),
  ($t$LAW25.14.1-L0-24$t$, $t$Consent$t$, $t$CON$t$, $t$LAW25.14.1$t$, $t$Is consent clear, free and informed, given for specific purposes, and requested for each purpose in simple and clear language?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 14$t$, 24),
  ($t$LAW25.14.2-L0-25$t$, $t$Consent$t$, $t$CON$t$, $t$LAW25.14.2$t$, $t$When consent is requested in writing, is the request presented separately from any other information provided to the person, and is assistance given on request to help the person understand its scope?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 14$t$, 25),
  ($t$LAW25.14.3-L0-26$t$, $t$Consent$t$, $t$CON$t$, $t$LAW25.14.3$t$, $t$Is consent treated as valid only for the time necessary to achieve the purposes for which it was requested?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 14$t$, 26),
  ($t$LAW25.12.1-L0-27$t$, $t$Consent$t$, $t$CON$t$, $t$LAW25.12.1$t$, $t$Is express consent obtained before sensitive personal information (such as medical, biometric or other intimate information) is used or communicated for a purpose other than the one for which it was collected?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 12$t$, 27),
  ($t$LAW25.4.1-L0-28$t$, $t$Consent$t$, $t$CON$t$, $t$LAW25.4.1$t$, $t$Is personal information concerning a minor under 14 years of age collected only with the consent of the person having parental authority or the tutor, unless collection is clearly for the minor's benefit?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 4.1$t$, 28),
  ($t$LAW25.8.4-L0-29$t$, $t$Consent$t$, $t$CON$t$, $t$LAW25.8.4$t$, $t$Can a person withdraw consent to the communication or use of the information collected, and does the organization have a procedure to act on the withdrawal?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 8$t$, 29),
  ($t$LAW25.12.2-L0-30$t$, $t$Use, Accuracy & Automated Decisions$t$, $t$USE$t$, $t$LAW25.12.2$t$, $t$Is personal information used only for the purposes for which it was collected, unless the person consents or an exception provided by law applies (for example a consistent purpose, or use clearly for the person's benefit)?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 12$t$, 30),
  ($t$LAW25.12.3-L0-31$t$, $t$Use, Accuracy & Automated Decisions$t$, $t$USE$t$, $t$LAW25.12.3$t$, $t$Where personal information is used without consent for study, research or the production of statistics, is it de-identified beforehand, and are reasonable measures taken to limit the risk of re-identification?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 12$t$, 31),
  ($t$LAW25.11-L0-32$t$, $t$Use, Accuracy & Automated Decisions$t$, $t$USE$t$, $t$LAW25.11$t$, $t$Does the organization ensure that personal information used to make a decision about a person is up to date and accurate at the time of the decision?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 11$t$, 32),
  ($t$LAW25.12.1.1-L0-33$t$, $t$Use, Accuracy & Automated Decisions$t$, $t$USE$t$, $t$LAW25.12.1.1$t$, $t$Where a decision is based exclusively on automated processing of personal information, is the person informed of this no later than when the decision is communicated?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 12.1$t$, 33),
  ($t$LAW25.12.1.2-L0-34$t$, $t$Use, Accuracy & Automated Decisions$t$, $t$USE$t$, $t$LAW25.12.1.2$t$, $t$On request, can the organization tell the person which personal information was used to render an automated decision, the reasons and principal factors and parameters that led to it, and the right to have that information rectified?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 12.1$t$, 34),
  ($t$LAW25.12.1.3-L0-35$t$, $t$Use, Accuracy & Automated Decisions$t$, $t$USE$t$, $t$LAW25.12.1.3$t$, $t$Is the person given the opportunity to submit observations to a member of personnel who is in a position to review an automated decision?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 12.1$t$, 35),
  ($t$LAW25.13-L0-36$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.13$t$, $t$Is personal information communicated to third persons only with the consent of the person concerned, or where the Act expressly authorizes communication without consent?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 13$t$, 36),
  ($t$LAW25.17.1-L0-37$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.17.1$t$, $t$Before communicating personal information outside Québec, or entrusting its collection, use, communication or keeping to a person or body outside Québec, does the organization conduct a privacy impact assessment?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 17$t$, 37),
  ($t$LAW25.17.2-L0-38$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.17.2$t$, $t$Does that assessment take into account the sensitivity of the information, the purposes of its use, the protection measures (including contractual ones) that would apply, and the legal framework of the State concerned?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 17$t$, 38),
  ($t$LAW25.17.3-L0-39$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.17.3$t$, $t$Is information communicated outside Québec only where the assessment establishes that it would receive adequate protection, and under a written agreement that takes the assessment's results into account?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 17$t$, 39),
  ($t$LAW25.18.3.1-L0-40$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.18.3.1$t$, $t$Where personal information is communicated without consent to a service provider or mandatary for a mandate or contract, is the mandate or contract in writing and does it specify the measures to protect confidentiality, limit use to the mandate, and prohibit keeping the information after expiry?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 18.3$t$, 40),
  ($t$LAW25.18.3.2-L0-41$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.18.3.2$t$, $t$Do service providers undertake to notify the person in charge without delay of any violation or attempted violation of confidentiality, and to allow the organization to carry out any verification relating to confidentiality?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 18.3$t$, 41),
  ($t$LAW25.18.4-L0-42$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.18.4$t$, $t$Where personal information is communicated for the purposes of concluding a commercial transaction, is there an agreement limiting its use to the transaction, protecting its confidentiality and requiring its destruction if the transaction is not concluded?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 18.4$t$, 42),
  ($t$LAW25.21-L0-43$t$, $t$Disclosure & Transfers$t$, $t$DIS$t$, $t$LAW25.21$t$, $t$Where personal information is communicated without consent for study, research or the production of statistics, is a privacy impact assessment conducted and a written agreement concluded with the recipient before communication?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 21$t$, 43),
  ($t$LAW25.23.1-L0-44$t$, $t$Retention, Destruction & Anonymization$t$, $t$RET$t$, $t$LAW25.23.1$t$, $t$Once the purposes for which personal information was collected or used are achieved, is it destroyed, subject to any preservation period provided for by an Act?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 23$t$, 44),
  ($t$LAW25.23.2-L0-45$t$, $t$Retention, Destruction & Anonymization$t$, $t$RET$t$, $t$LAW25.23.2$t$, $t$Where personal information is anonymized instead of destroyed, is it for a serious and legitimate purpose, and is anonymization carried out according to generally accepted best practices and the criteria set by regulation so that the person can no longer be identified, irreversibly?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 23$t$, 45),
  ($t$LAW25.3.2.4-L0-46$t$, $t$Retention, Destruction & Anonymization$t$, $t$RET$t$, $t$LAW25.3.2.4$t$, $t$Are retention periods and destruction methods defined for each category of personal information and applied in the systems that hold it?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 3.2$t$, 46),
  ($t$LAW25.10.1-L0-47$t$, $t$Security Safeguards$t$, $t$SEC$t$, $t$LAW25.10.1$t$, $t$Has the organization taken the security measures necessary to protect personal information collected, used, communicated, kept or destroyed, reasonable given its sensitivity, the purposes for which it is used, its quantity, distribution and medium?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 10$t$, 47),
  ($t$LAW25.10.2-L0-48$t$, $t$Security Safeguards$t$, $t$SEC$t$, $t$LAW25.10.2$t$, $t$Are security measures reviewed when the sensitivity, volume or medium of the personal information held changes?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 10$t$, 48),
  ($t$LAW25.27.1-L0-49$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.27.1$t$, $t$On request, does the organization confirm the existence of personal information it holds about a person, communicate it, and allow the person to obtain a copy?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 27$t$, 49),
  ($t$LAW25.27.2-L0-50$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.27.2$t$, $t$Can computerized personal information collected from the applicant be communicated in a structured, commonly used technological format, to the applicant or to a person or body authorized by law to collect it, when requested (data portability)?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 27$t$, 50),
  ($t$LAW25.28-L0-51$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.28$t$, $t$Can a person have inaccurate, incomplete or equivocal personal information rectified, and have information deleted where its collection, communication or keeping is not authorized by law?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 28$t$, 51),
  ($t$LAW25.28.1-L0-52$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.28.1$t$, $t$Does the organization have a procedure to cease disseminating personal information, or to de-index or re-index a hyperlink attached to a person's name, where dissemination contravenes the law or a court order or causes serious injury?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 28.1$t$, 52),
  ($t$LAW25.32-L0-53$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.32$t$, $t$Are access and rectification requests answered in writing within 30 days of receipt?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 32$t$, 53),
  ($t$LAW25.34-L0-54$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.34$t$, $t$Is every refusal of a request given in writing with reasons, the provision of law relied on, the remedies available and the time limit for exercising them, with help to understand the refusal on request?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 34$t$, 54),
  ($t$LAW25.33-L0-55$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.33$t$, $t$Is access to personal information free of charge, with only a reasonable charge for transcription, reproduction or transmission that is announced to the applicant in advance?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 33$t$, 55),
  ($t$LAW25.30-L0-56$t$, $t$Individual Rights$t$, $t$RGT$t$, $t$LAW25.30$t$, $t$Is the identity of an applicant, or their authority to act as representative, heir or person having parental authority, verified before personal information is released?$t$, $t$Act respecting the protection of personal information in the private sector (CQLR c. P-39.1), s. 30$t$, 56),
  ($t$LAW25.IT44.1-L0-57$t$, $t$Biometrics$t$, $t$BIO$t$, $t$LAW25.IT44.1$t$, $t$Is express consent obtained before a person's identity is verified or confirmed by a process that captures biometric characteristics or measurements, and is an alternative means of identification offered?$t$, $t$Act to establish a legal framework for information technology, s. 44$t$, 57),
  ($t$LAW25.IT44.2-L0-58$t$, $t$Biometrics$t$, $t$BIO$t$, $t$LAW25.IT44.2$t$, $t$Is the Commission d'accès à l'information notified before biometric characteristics or measurements are used to verify or confirm identity?$t$, $t$Act to establish a legal framework for information technology, s. 44$t$, 58),
  ($t$LAW25.IT45-L0-59$t$, $t$Biometrics$t$, $t$BIO$t$, $t$LAW25.IT45$t$, $t$Is the creation of a database of biometric characteristics and measurements disclosed to the Commission d'accès à l'information no later than 60 days before it is brought into service?$t$, $t$Act to establish a legal framework for information technology, s. 45$t$, 59)
) AS v(req_code, domain, domain_code, standard, req_text, guidance, sort_order)
WHERE f.code = 'QC_LAW25'
ON CONFLICT (framework_id, req_code) DO NOTHING;

-- Same level and status configuration as the other compliance-only frameworks (copied from PIPEDA).
INSERT INTO bayanat.gov_compliance_level_config (framework_id, level_num, name, color_hex, description)
SELECT n.framework_id, c.level_num, c.name, c.color_hex, c.description
FROM bayanat.gov_compliance_level_config c
JOIN bayanat.gov_compliance_frameworks p ON p.framework_id = c.framework_id AND p.code = 'PIPEDA'
CROSS JOIN bayanat.gov_compliance_frameworks n
WHERE n.code = 'QC_LAW25'
  AND NOT EXISTS (SELECT 1 FROM bayanat.gov_compliance_level_config x WHERE x.framework_id = n.framework_id);

INSERT INTO bayanat.compliance_config_items (framework_id, config_group, code, label, label_ar, color_hex, sort_order)
SELECT n.framework_id, c.config_group, c.code, c.label, c.label_ar, c.color_hex, c.sort_order
FROM bayanat.compliance_config_items c
JOIN bayanat.gov_compliance_frameworks p ON p.framework_id = c.framework_id AND p.code = 'PIPEDA'
CROSS JOIN bayanat.gov_compliance_frameworks n
WHERE n.code = 'QC_LAW25'
  AND NOT EXISTS (SELECT 1 FROM bayanat.compliance_config_items x WHERE x.framework_id = n.framework_id);

COMMIT;
